mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('votings.urls')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'votings.views.page_not_found'

mysite/users/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('create_user/', views.CreateUserView.as_view(), name="create_user"),
    path('login/', views.LoginUserView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('<slug:username>/show_profile/', views.ShowProfileView.as_view(), name="show_profile"),
]

mysite/templates/base.html
{% load static %}


<!DOCTYPE html>
<html>
	<head>
			{% block title %}block title{% endblock title %}
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<link type="text/css" href="{% static 'css/styles.css' %}" rel="stylesheet" />
	</head>
	<body>
		<div>
			{% block h1 %}block h1{% endblock h1 %}
		</div>
		<div class="toc">
			{% spaceless %}
			<a href="{% url 'index' %}">Главная страница</a>
			<a href="{% url 'program' %}">Программа</a>
			<a href="{% url 'users:create_user' %}">Регистрация</a>
			<a href="{% url 'users:login' %}">Вход</a>
			{% if not user.is_anonymous %}
				<a href="{% url 'users:logout' %}">Выход</a>
				<a href="{% url 'votings_list' %}">Список голосований</a>
				<a href="{% url 'create_voting' %}">Создать голосование</a>
				<a href="{% url 'users:show_profile' user.username %}">Профиль</a>
			{% endif %}
			{% endspaceless %}
		</div>
		<div class="content">
			{% block content %}block content{% endblock content %}
		</div>
	</body>
</html>